"""Initial migration with base models

Revision ID: bf7954d027a0
Revises:
Create Date: 2025-04-01 15:47:14.842987

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bf7954d027a0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
