name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: extractions/setup-just@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Lint with Ruff
        run: |
          source .venv/bin/activate
          ruff check .

      - name: Format with Ruff
        run: |
          source .venv/bin/activate
          ruff format --check .

      - name: Type check with Pyright
        run: |
          source .venv/bin/activate
          pyright

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          just test-cov
